services:
  - type: web
    name: eduassess-platform
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: eduassess-db
          property: connectionString
    autoDeploy: false

databases:
  - name: eduassess-db
    databaseName: eduassess
    user: eduassess_user
    plan: free